version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: bn_db
    environment:
      - POSTGRES_USER=baca_user
      - POSTGRES_PASSWORD=baca_pass
      - POSTGRES_DB=baca_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - baca_net

  backend:
    build: ./backend
    container_name: bn_be
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=baca_user
      - DB_PASSWORD=baca_pass
      - DB_NAME=baca_db
    depends_on:
      - db
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - baca_net

  frontend:
    build: ./frontend
    container_name: bn_fe
    ports:
      - "3333:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - baca_net

  admin:
    build: ./admin
    container_name: bn_admin
    ports:
      - "3000:80"
    tty: true
    volumes:
      - ./admin:/app
      - /app/node_modules   
    networks:
      - baca_net

volumes:
  postgres_data:
  node_modules:

networks:
  baca_net:
